# Generated by Django 5.1.4 on 2024-12-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_orderitem_orderfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='your_order',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
