# Generated by Django 5.1.4 on 2025-01-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_your_order_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderfood',
            new_name='Orderitem',
        ),
    ]
